Using prior on all camera poses.
borglab/gtsfm pull request #182
Opened 2021-05-25 22:02 UTC by ayushbaid

As we use rotation and translation modules in our pipelines, we have a pretty strong prior on the camera parameters. I think this was suggested by @dellaert quite a while back too.

The metrics do not have any significant difference.

Old:
```
[2021-05-25 14:46:02,542 DEBUG data_assoc.py line 133 198494] [Data association] output number of tracks: 8965
[2021-05-25 14:46:02,542 DEBUG data_assoc.py line 134 198494] [Data association] output avg. track length: 5.23
[2021-05-25 14:46:03,204 INFO bundle_adjustment.py line 48 198495] Input: 8965 tracks on 12 cameras

[2021-05-25 14:46:09,476 INFO bundle_adjustment.py line 113 198495] initial error: 29036343.05
[2021-05-25 14:46:09,477 INFO bundle_adjustment.py line 114 198495] final error: 24937.02
[2021-05-25 14:46:15,056 INFO bundle_adjustment.py line 121 198495] [Result] Number of tracks before filtering: 8965
[2021-05-25 14:46:16,466 INFO bundle_adjustment.py line 129 198495] [Result] Number of tracks after filtering: 8926
[2021-05-25 14:46:16,466 INFO bundle_adjustment.py line 130 198495] [Result] Mean track length 5.230
[2021-05-25 14:46:16,466 INFO bundle_adjustment.py line 131 198495] [Result] Median track length 4.000
[2021-05-25 14:46:16,929 INFO gtsfm_data.py line 308 198495] Min scene reproj error: 0.000
[2021-05-25 14:46:16,929 INFO gtsfm_data.py line 309 198495] Avg scene reproj error: 0.171
[2021-05-25 14:46:16,930 INFO gtsfm_data.py line 310 198495] Median scene reproj error: 0.136
[2021-05-25 14:46:16,930 INFO gtsfm_data.py line 311 198495] Max scene reproj error: 2.949
```

New:
```
[2021-05-25 14:51:24,342 DEBUG data_assoc.py line 133 198977] [Data association] output number of tracks: 8965
[2021-05-25 14:51:24,342 DEBUG data_assoc.py line 134 198977] [Data association] output avg. track length: 5.23
[2021-05-25 14:51:25,229 INFO bundle_adjustment.py line 48 198975] Input: 8965 tracks on 12 cameras

[2021-05-25 14:51:31,396 INFO bundle_adjustment.py line 108 198975] initial error: 29036343.05
[2021-05-25 14:51:31,397 INFO bundle_adjustment.py line 109 198975] final error: 24938.42
[2021-05-25 14:51:36,055 INFO bundle_adjustment.py line 116 198975] [Result] Number of tracks before filtering: 8965
[2021-05-25 14:51:39,279 INFO bundle_adjustment.py line 124 198975] [Result] Number of tracks after filtering: 8926
[2021-05-25 14:51:39,279 INFO bundle_adjustment.py line 125 198975] [Result] Mean track length 5.230
[2021-05-25 14:51:39,279 INFO bundle_adjustment.py line 126 198975] [Result] Median track length 4.000
[2021-05-25 14:51:39,714 INFO gtsfm_data.py line 308 198975] Min scene reproj error: 0.000
[2021-05-25 14:51:39,715 INFO gtsfm_data.py line 309 198975] Avg scene reproj error: 0.171
[2021-05-25 14:51:39,716 INFO gtsfm_data.py line 310 198975] Median scene reproj error: 0.136
[2021-05-25 14:51:39,716 INFO gtsfm_data.py line 311 198975] Max scene reproj error: 2.949
```

2021-05-26 01:41 UTC, akshay-krishnan requested changes

2021-05-26 01:41 UTC, akshay-krishnan commented on gtsfm/bundle/bundle_adjustment.py
> +                    initial_data.get_camera(valid_camera_indices[0]),
Please correct the indices.

2021-09-03 03:57 UTC, johnwlambert commented
@ayushbaid can you pull master into this branch, so we can check the metrics and see if this is something we would like to do?

2021-09-06 00:55 UTC, ayushbaid commented
The main hypothesis behind this PR is: "We have good pose from the averaging module, and hence we can use a prior on them to preserve them and not be corrupted by outlier tracks in bundle adjustment."

Let's compare the angular rotation and translation errors after averaging and after BA in the baseline:

# Door-12 dataset

| Metric | Post-averaging | Post-BA |
| ------- | -------------- | ------ |
| Mean rotation angular error |  0.115 |  0.029 |
| Median rotation angular error  | 0.095 | 0.024 |
| Mean translation angular error |  0.976 |  0.649  |
| Median translation angular error |  0.594 | 0.013 |

# Skydio-32 dataset

| Metric | Post-averaging | Post-BA |
| ------- | -------------- | ------ |
| Mean rotation angular error |   7.95404  |  9.022 |
| Median rotation angular error  | 5.5387 | 8.882 |
| Mean translation angular error |  14.1855 |  8.818  |
| Median translation angular error | 8.085 | 7.1398 |

2021-09-06 01:05 UTC, ayushbaid commented
For the new changes, here are the metrics:

# Skydio-32 dataset


| Metric | Post-averaging | Post-BA |
| ------- | -------------- | ------ |
| Mean rotation angular error |   7.95404  |  8.409 |
| Median rotation angular error  | 5.539 | 7.533 |
| Mean translation angular error |  13.9015 |  8.366  |
| Median translation angular error | 7.678| 6.797 |

2021-09-06 01:06 UTC, ayushbaid commented
The metrics on the pose errors do not point to any major change. Maybe we need metrics to judge the "correctness" of 3D points too?

2021-09-11 22:38 UTC, ayushbaid commented
Not a priority right now.

2021-09-11 22:38 UTC, closed without merging