GtsfmMetric with no ground truth pose
borglab/gtsfm pull request #243
Opened 2021-08-31 16:03 UTC by travisdriver

# What

Error thrown in `metrics.py` if ground truth pose not provided to the `TwoViewEstimator`. 

# Why

If `gt_i2Ti1` is `None` (i.e., when ground truth poses aren't available) in [`scene_optimizer.py`](https://github.com/borglab/gtsfm/blob/b77cf9d4cfb4d0b3ad662dc7dcfeebebb2bb3814/gtsfm/scene_optimizer.py#L127), then the lists `rot3_angular_errors` and `trans_angular_errors` in [`aggregate_frontend_metrics`](https://github.com/borglab/gtsfm/blob/b77cf9d4cfb4d0b3ad662dc7dcfeebebb2bb3814/gtsfm/two_view_estimator.py#L299) are filled with `NaN` since there is no ground truth pose to compare against. 

When this list is passed to [`GtsfmMetrics._create_summary()`](https://github.com/borglab/gtsfm/blob/b77cf9d4cfb4d0b3ad662dc7dcfeebebb2bb3814/gtsfm/evaluation/metrics.py#L154), an exception is thrown, as `np.nanmedian(data)` returns `np.NaN`. For some reason, this only happens with `np.nanmedian()` and not any of the other `np.nan*` functions. Here's the specific error:

```
Traceback (most recent call last):
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 80, in <module>
    run_scene_optimizer(args)
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 42, in run_scene_optimizer
    sfm_result = sfm_result_graph.compute()
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2707, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2021, in gather
    return self.sync(
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 862, in sync
    return sync(
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    raise exc.with_traceback(tb)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 321, in f
    result[0] = yield future
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 1886, in _gather
    raise exception.with_traceback(traceback)
  File "/home/tdriver6/Documents/gtsfm/gtsfm/two_view_estimator.py", line 371, in aggregate_frontend_metrics
    GtsfmMetric("rot3_angular_errors_deg", rot3_angular_errors),
  File "/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py", line 113, in __init__
    self._summary = self._create_summary(data)
  File "/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py", line 176, in _create_summary
    "median": np.nanmedian(data).tolist(),
AttributeError: 'float' object has no attribute 'tolist'
```

# How

Set `gt_pose_graph = None` in the `SceneOptimizer`.

# Fix

Check for list of all `NaN` in `GtsfmMetric._create_summary()`.

2021-08-31 23:20 UTC, johnwlambert commented
Thanks for finding this.

@akshay-krishnan @ayushbaid maybe an easier fix is just to cast the array to NaN before calling nanmean and .tolist()?

because if we cast it to float, the None's turn into Nan's

2021-09-01 00:37 UTC, akshay-krishnan commented
Its a nice to have check in metrics.py. 

But more importantly, 
> If gt_i2Ti1 is None (i.e., when ground truth poses aren't available) in scene_optimizer.py, then the lists rot3_angular_errors and trans_angular_errors in aggregate_frontend_metrics are filled with NaN since there is no ground truth pose to compare against.

Why are rot3_angular_errors and trans_angular_errors not empty if gt_i2Ti1 is None?

2021-09-01 00:38 UTC, akshay-krishnan commented
We cannot compute metrics if ground truth is not available, and an empty metric.json seems better to me than one full of NaNs.

2021-09-01 00:43 UTC, johnwlambert commented
I think this is an issue that randomly arises. I just tried running
```
python gtsfm/runner/run_scene_optimizer.py --dataset_root /Users/johnlambert/Downloads/skydio_crane_mast_8imgs_with_exif  --config_name sift_front_end.yaml --image_extension jpg
```
i.e. without ground truth, and i had no issues

2021-09-01 00:48 UTC, travisdriver commented
> We cannot compute metrics if ground truth is not available, and an empty metric.json seems better to me than one full of NaNs. 

I agree.

2021-09-01 00:49 UTC, johnwlambert commented
Will the plotting code support an empty metric.json @akshay-krishnan ?

2021-09-01 00:51 UTC, travisdriver commented
> I think this is an issue that randomly arises. I just tried running
> 
> ```
> 
> python gtsfm/runner/run_scene_optimizer.py --dataset_root /Users/johnlambert/Downloads/skydio_crane_mast_8imgs_with_exif  --config_name sift_front_end.yaml --image_extension jpg
> 
> ```
> 
> i.e. without ground truth, and i had no issues

Can you verify that gt_i2Ti1 is actually being set to None? It was consistently throwing the error for me. 

However, I was explicitly setting gt_i2Ti1 to None in the code to get the error.

2021-09-01 01:02 UTC, akshay-krishnan commented
> Will the plotting code support an empty metric.json @akshay-krishnan ?

I think it should, though Ive never tested it for that case. On the other hand, NaN might cause problems. Not sure what plotly behavior is.

2021-09-01 02:41 UTC, johnwlambert commented
we can break the GtsfmMetric with the following input, which is not all Nan:
````python
[0.4943377406921827, 0.07750727215807857, None, 50.555624633887966, 0.4105653459580154, None, None, 0.9000904523273447, 0.15871712683215253, 0.15871712683215253, None, 59.3105749901508, None, None, 51.9263925451782, 0.43754308753149673, None, None, None, 14.6315526920527, 0.21327828059175513, None, 0.9918309430987753, 56.119727462062144, None, 0.3621078266499683, 0.4472408970491756, None, 58.22164813611213, 0.3006139727821833, 14.261747655390911, 0.0671259818866646, None, None, 0.5664233549647623, None, None, None, 148.0883061815312, 12.91579810943746, 0.7360540870336185, 17.466692579267853, None, None, 0.3819295377487452, None, None, None, None, None, None, None, 83.09188463926506, 132.1501107697091, 61.95121409942072, None, None, 0.8222581405138006, None, 13.870623909694004, 2.3944521928979157, 1.0233763046419453, 0.5530423137260041, None, 0.6370692774459146, 52.60742424439034, 76.49839361884142, None, 0.015624169349058772, 0.21313872058968922, 63.56032366636337, 44.590997477954126, 1.360514959048976, None, None, None, 0.8176972123560743, 1.7802700119952475, 50.83076687024327, 0.9443750223562086, None, 202.97745202897553, None, None, 55.983760841138086, None, 1.302481423890915, 40.5853296607991, 48.42931630879821, None, None, None, None, None, None, None, None, 0.033959743154501135, 12.9681951765307, 59.42115611552481, None, None, None, None, None, 61.091701437662984, 1.2437783462313932, None, None, 1.240393629977256, 1.651192162791904, 40.17396605086019, None, None, None, None, None, 49.801235828014114, None, None, None, None, 50.03677057534568, 0.5075587943615103, 10.469703770781683, None, 0.08808336230590988, 16.153933793811515, None, None, None, None, 1.586955293605011, None, None, None, 68.03680428815329, None, None, 15.61341378263616, None, None, 1.5588061165025615, None, None, None, 0.8248050265929598, None, None, 0.9535105707447128, 65.35440574210394, None, None, None, None, None, 26.413890455853974, None, None, None, None, None, None, None, 0.7792212046059535, 1.0127438965328188, 30.35567191409832, 1.1853470965752986, 1.1327289766656823, 1.1327289766656823, None, None, 0.42001167737529194, 43.168979909097644, 0.3642699379899129, None, None, None, None, None, 0.4261163184497169, 0.16415585103475988, 1.8602169640364163, None, None, 1.13233231583566, None, None, None, 49.58969698727923, None, 1.0519967746086047, None, None, None, None, None, None, 9.59263054694744, None, 0.30806994360876555, None, None, None, 1.0437588974020489, None, None, 58.78194046423858, None, None, None, None, None, 0.9874643561474854, None, None, 0.6131299784143841, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 66.46401037099093, None, 66.6955274609439, 54.669822067745486, 55.17922651462939, 69.87349434202932, 57.759502723432, 77.86671094388306, 63.332476527915084, 67.46438960663443, 68.04055952245828, 63.8183238347731, 61.995788004439056, 57.06676503719942, 117.34364801340809, 54.38664691039051, 48.796188421425114, 54.89732058977566, 94.00860838321012, 59.0200093750054, 59.0200093750054, 69.34760266811942, 64.79997392101124, 84.41607280868489, 58.36297124399549, 168.79449299132395, 65.63034137441863, 59.357135716984565, 67.1993421410266, 165.513021980967, 66.06800326382204, 66.74712871699721, 69.35305799630743, 62.91264113157705, 60.573526293358086, 62.559662127564, 75.28845267460494, 78.69054745115363, 52.024653091842, 66.25064831275029, 90.71494123478597, 61.40723026534052, 72.16403743783756, 64.88160899077072, 60.51516366299165, 77.29749162397363, 65.27902999640833, 77.20329897784379, 77.20329897784379, 66.49081389499872, 82.33645045675817, 82.33645045675817, 58.65133076776472, 133.97987102335523, 50.47608281217831, 63.521288139444025, 72.4023678255227, 78.90154077634892, 119.5793620474521, 77.69101347493815, 48.03075700997626, 66.22373950538287, 67.35151841452496, 58.577541118242024, 74.02249636838114, 65.24717087545461, 60.07683624148301, 72.96818748880266, 72.96818748880266, 67.27636740749027, 67.28206613585273, 65.74015407237015, 66.52494646857765, 56.23454470104585, 78.32687431048359, 67.06280783456234, 70.66722739039422, 66.2771477046032, 63.51513242622042, 59.448951639963774, 60.15790922475607, 72.35065703652525, 81.01768505504633, 69.32571654247353, 80.06376575162106, 55.27681477310521, 66.08158555618016, 70.61484138279407, 59.138890712201864, 51.78146471756806, 71.93163080820003, 72.36927659559582, 63.30583544290206, 62.83273308938842, 82.69501610675087, 56.389601159341645, 72.7481894734897, 75.96670522073885, 111.70917409697644, 51.697936791223356, 66.89623260038638, 68.62706887381286, 66.09997275625621, 102.63885953676669, 64.1644364774806, 74.936675628081, 75.29507328938584, 228.6755326553307, 89.74304647560503, 64.86054899681288, 121.51143406751599, 56.83633830846588, 81.89165871625944, 81.90315809855448, 61.70851904394595, 48.185344531491886, 68.47136692217632, 63.2162352926918, 55.4524720464402, 54.76547313998529, 70.39501189663703, 79.30251499788227, 72.91173310992036, 70.53569339077895, 65.28546015553816, 82.83618652798602, 80.83172393466307, 66.40564770487826, 254.64207315496236, 83.08876187437372, 94.99338162555573, 167.60005904213136, 54.46975197282207, 95.50829929231524, 149.09894641442233, 113.76080029479617, 84.36069469089453, 101.24582869004921, 69.85244282889329]
```

2021-09-01 02:54 UTC, travisdriver commented
What's the specific error?

2021-09-01 03:00 UTC, johnwlambert commented
here is the exact error:

```
distributed.worker - WARNING - Compute Failed
Function:  execute_task
args:      ((<bound method DataAssociation.run of DataAssociation(reproj_error_thresh=100, min_track_len=2, mode=<TriangulationParam.NO_RANSAC: 0>, num_ransac_hypotheses=20, save_track_patches_viz=False)>, 8, {1: .pose R: [
	-0.666108, -0.550273, 0.503487;
	0.552477, -0.817521, -0.162567;
	0.501068, 0.169878, 0.848571
]
t: -1.42454  1.02067 0.120821
.calibration.K[583.1175; 0; 0; 507; 380];
, 2: .pose R: [
	-0.797680111, -0.558884097, 0.226616431;
	0.583932899, -0.809687116, 0.0585588913;
	0.150760771, 0.179040053, 0.972222119
]
t:  -0.800568819   0.572387209 -0.0664739823
.calibration.K[583.1175; 0; 0; 507; 380];
, 3: .pose R: [
	-0.82444263, -0.550926242, 0.129516889;
	0.564574657, -0.816538202, 0.120502368;
	0.0393675711, 0.172469242, 0.984227898
]
t: -0.794390669  0.567679952 -0.067297119
.calibration.K[583.1175; 0; 0; 507; 380];
, 4: .pose R: [
	-0.819192511, -0.548180012, 0.16858916;
	0.565370194, -0.821250678, 0.076836626;
	0.0963336591, 0.158259274, 0.982687045
]
t: -1.98453271e-05  -0.00
kwargs:    {}
Exception: TypeError("'<=' not supported between instances of 'float' and 'NoneType'")

Traceback (most recent call last):
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 80, in <module>
    run_scene_optimizer(args)
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 42, in run_scene_optimizer
    sfm_result = sfm_result_graph.compute()
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 286, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 568, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2671, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 1948, in gather
    return self.sync(
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 845, in sync
    return sync(
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 326, in sync
    raise exc.with_traceback(tb)
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 309, in f
    result[0] = yield future
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 1813, in _gather
    raise exception.with_traceback(traceback)
  File "/home/runner/work/gtsfm/gtsfm/gtsfm/data_association/data_assoc.py", line 158, in run
    GtsfmMetric("rejected_track_avg_errors_px", per_rejected_track_avg_errors, store_full_data=False),
  File "/home/runner/work/gtsfm/gtsfm/gtsfm/evaluation/metrics.py", line 113, in __init__
    self._summary = self._create_summary(data)
  File "/home/runner/work/gtsfm/gtsfm/gtsfm/evaluation/metrics.py", line 174, in _create_summary
    "min": np.nanmin(data).tolist(),
  File "<__array_function__ internals>", line 5, in nanmin
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 326, in nanmin
    res = np.amin(a, axis=axis, out=out, **kwargs)
  File "<__array_function__ internals>", line 5, in amin
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2879, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/usr/share/miniconda3/envs/gtsfm-v1/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
TypeError: '<=' not supported between instances of 'float' and 'NoneType'
Error: Process completed with exit code 1.
0s
```

2021-09-01 03:05 UTC, johnwlambert commented
for example, this test will fail @akshay-krishnan 
``python
    def test_array_input_with_none_entries(self) -> None:
        """ """
        per_rejected_track_avg_errors = [0.4943377406921827, 0.07750727215807857, None, 50.555624633887966, 0.4105653459580154, None, None]
        metric = GtsfmMetric("rejected_track_avg_errors_px", per_rejected_track_avg_errors, store_full_data=False)

```

2021-09-01 13:41 UTC, travisdriver commented
Do I need to change anything, or is this PR good to go?

2021-09-01 13:50 UTC, johnwlambert commented
@travisdriver could you give a minimal example that can reproduce it? I'm still not able to reproduce it on my machine.

2021-09-01 13:56 UTC, travisdriver commented
Modify [this conditional statement](https://github.com/borglab/gtsfm/blob/72ead7f826b850f4637bbd0f96204eab10b271cb/gtsfm/scene_optimizer.py#L126) such that `gt_i1Ti1` is always `None`.

2021-09-06 15:59 UTC, johnwlambert commented
Hi Travis, I tried out 
```
python gtsfm/runner/run_scene_optimizer.py --dataset_root /Users/johnlambert/Downloads/skydio_crane_mast_8imgs_with_exif  --image_extension jpg --num_workers 2
```
and added to line 105 of the scene optimizer
```
        print("gt pose graph", gt_pose_graph)
```
it printed out `gt pose graph None`. But I didnt see a crash or error raised.

2021-09-06 16:00 UTC, johnwlambert commented
when I run the following, I see:
```python
pytest -v tests/evaluation/metrics_test.py

======================================================================================== test session starts =========================================================================================
platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/johnlambert/miniconda3/envs/gtsfm-v1/bin/python
cachedir: .pytest_cache
rootdir: /Users/johnlambert/Downloads/gtsfm
plugins: hydra-core-1.1.0
collected 10 items                                                                                                                                                                                   

tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_1d_distribution_metric PASSED                                                                                                   [ 10%]
tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_scalar_metric PASSED                                                                                                            [ 20%]
tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution PASSED                                                                                                [ 30%]
tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution_histogram PASSED                                                                                      [ 40%]
tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_no_full_data PASSED                                                                                                   [ 50%]
tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_scalar PASSED                                                                                                         [ 60%]
tests/evaluation/metrics_test.py::TestGtsfmMetric::test_saves_to_json PASSED                                                                                                                   [ 70%]
tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_get_metric_as_dict PASSED                                                                                                        [ 80%]
tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_parse_metrics_from_dict PASSED                                                                                                   [ 90%]
tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_saves_to_json PASSED                                                                                                             [100%]

========================================================================================= 10 passed in 0.62s =========================================================================================
(gtsfm-v1) johnlambert@hayoungs-mbp gtsfm % 
```

2021-09-06 16:03 UTC, travisdriver commented
> when I run the following, I see:
> 
> ```python
> pytest -v tests/evaluation/metrics_test.py
> 
> ======================================================================================== test session starts =========================================================================================
> platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/johnlambert/miniconda3/envs/gtsfm-v1/bin/python
> cachedir: .pytest_cache
> rootdir: /Users/johnlambert/Downloads/gtsfm
> plugins: hydra-core-1.1.0
> collected 10 items                                                                                                                                                                                   
> 
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_1d_distribution_metric PASSED                                                                                                   [ 10%]
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_scalar_metric PASSED                                                                                                            [ 20%]
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution PASSED                                                                                                [ 30%]
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution_histogram PASSED                                                                                      [ 40%]
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_no_full_data PASSED                                                                                                   [ 50%]
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_scalar PASSED                                                                                                         [ 60%]
> tests/evaluation/metrics_test.py::TestGtsfmMetric::test_saves_to_json PASSED                                                                                                                   [ 70%]
> tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_get_metric_as_dict PASSED                                                                                                        [ 80%]
> tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_parse_metrics_from_dict PASSED                                                                                                   [ 90%]
> tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_saves_to_json PASSED                                                                                                             [100%]
> 
> ========================================================================================= 10 passed in 0.62s =========================================================================================
> (gtsfm-v1) johnlambert@hayoungs-mbp gtsfm % 
> ```
> 
> what do you see on your side? maybe i am using an outdated version of the env?

Where is `test_create_all_nan_metric()`?

The unit test should fail if you remove the fix.

2021-09-06 16:04 UTC, travisdriver commented
> Hi Travis, I tried out
> 
> ```
> python gtsfm/runner/run_scene_optimizer.py --dataset_root /Users/johnlambert/Downloads/skydio_crane_mast_8imgs_with_exif  --image_extension jpg --num_workers 2
> ```
> 
> and added to line 105 of the scene optimizer
> 
> ```
>         print("gt pose graph", gt_pose_graph)
> ```
> 
> it printed out `gt pose graph None`. But I didnt see a crash or error raised.

2021-09-06 16:05 UTC, travisdriver commented
> Hi Travis, I tried out
> 
> ```
> python gtsfm/runner/run_scene_optimizer.py --dataset_root /Users/johnlambert/Downloads/skydio_crane_mast_8imgs_with_exif  --image_extension jpg --num_workers 2
> ```
> 
> and added to line 105 of the scene optimizer
> 
> ```
>         print("gt pose graph", gt_pose_graph)
> ```
> 
> it printed out `gt pose graph None`. But I didnt see a crash or error raised.

A lot has changed since I opened the PR a week ago. The unit test I added should still fail though.

2021-09-06 19:49 UTC, johnwlambert commented
> > when I run the following, I see:
> > ```python
> > pytest -v tests/evaluation/metrics_test.py
> > 
> > ======================================================================================== test session starts =========================================================================================
> > platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/johnlambert/miniconda3/envs/gtsfm-v1/bin/python
> > cachedir: .pytest_cache
> > rootdir: /Users/johnlambert/Downloads/gtsfm
> > plugins: hydra-core-1.1.0
> > collected 10 items                                                                                                                                                                                   
> > 
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_1d_distribution_metric PASSED                                                                                                   [ 10%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_scalar_metric PASSED                                                                                                            [ 20%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution PASSED                                                                                                [ 30%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution_histogram PASSED                                                                                      [ 40%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_no_full_data PASSED                                                                                                   [ 50%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_scalar PASSED                                                                                                         [ 60%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_saves_to_json PASSED                                                                                                                   [ 70%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_get_metric_as_dict PASSED                                                                                                        [ 80%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_parse_metrics_from_dict PASSED                                                                                                   [ 90%]
> > tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_saves_to_json PASSED                                                                                                             [100%]
> > 
> > ========================================================================================= 10 passed in 0.62s =========================================================================================
> > (gtsfm-v1) johnlambert@hayoungs-mbp gtsfm % 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > what do you see on your side? maybe i am using an outdated version of the env?
> 
> Where is `test_create_all_nan_metric()`?
> 
> The unit test should fail if you remove the fix.
> 
> Are you sure you're on the right branch?

I was running those unit tests on master -- that must have been why (I thought one of the pre-existing ones was failing).

Can we try to find a way to reproduce the original issue? The case where we get all NaNs out of the front-end? I think it's a more subtle reason that we need to dig into a bit more (maybe not necessarily having to do with the case where we have no ground truth pose).

2021-09-06 20:11 UTC, travisdriver commented
> > > when I run the following, I see:
> > > ```python
> > > pytest -v tests/evaluation/metrics_test.py
> > > 
> > > ======================================================================================== test session starts =========================================================================================
> > > platform darwin -- Python 3.8.10, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/johnlambert/miniconda3/envs/gtsfm-v1/bin/python
> > > cachedir: .pytest_cache
> > > rootdir: /Users/johnlambert/Downloads/gtsfm
> > > plugins: hydra-core-1.1.0
> > > collected 10 items                                                                                                                                                                                   
> > > 
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_1d_distribution_metric PASSED                                                                                                   [ 10%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_create_scalar_metric PASSED                                                                                                            [ 20%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution PASSED                                                                                                [ 30%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_1D_distribution_histogram PASSED                                                                                      [ 40%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_no_full_data PASSED                                                                                                   [ 50%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_parses_from_dict_scalar PASSED                                                                                                         [ 60%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetric::test_saves_to_json PASSED                                                                                                                   [ 70%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_get_metric_as_dict PASSED                                                                                                        [ 80%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_parse_metrics_from_dict PASSED                                                                                                   [ 90%]
> > > tests/evaluation/metrics_test.py::TestGtsfmMetricsGroup::test_saves_to_json PASSED                                                                                                             [100%]
> > > 
> > > ========================================================================================= 10 passed in 0.62s =========================================================================================
> > > (gtsfm-v1) johnlambert@hayoungs-mbp gtsfm % 
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > what do you see on your side? maybe i am using an outdated version of the env?
> > 
> > 
> > Where is `test_create_all_nan_metric()`?
> > The unit test should fail if you remove the fix.
> > Are you sure you're on the right branch?
> 
> I was running those unit tests on master -- that must have been why (I thought one of the pre-existing ones was failing).
> 
> Can we try to find a way to reproduce the original issue? The case where we get all NaNs out of the front-end? I think it's a more subtle reason that we need to dig into a bit more (maybe not necessarily having to do with the case where we have no ground truth pose).

Ok well can you run the new tests with and without the fix please. This at least shows that the `GtsfmData` without the fix is not able to handle all NaN input. I think it's a good check to have that won't hurt anything, and will prevent similar problems if they arise again in the future. 

Go ahead and start a new issue that references this one, but like I said, I can't reproduce the original error since all of the changes.

2021-09-07 16:08 UTC, travisdriver commented
This has seemed to resurface. I get the error when I run the following on `master`:

```shell
python gtsfm/runner/run_scene_optimizer_colmaploader.py --images_dir tests/data/crane_mast_8imgs/images/ --colmap_files_dirpath tests/data/crane_mast_8imgs/crane_mast_8imgs_colmap_output/ --max_frame_lookahead 8
```

Here's the full traceback:

```shell
/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py:174: RuntimeWarning: All-NaN slice encountered
  "min": np.nanmin/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py:174: RuntimeWarning: All-NaN slice encountered
  "min": np.nanmin(data).tolist(),
/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py:175: RuntimeWarning: All-NaN slice encountered
  "max": np.nanmax(data).tolist(),
/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1113: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
distributed.worker - WARNING - Compute Failed
Function:  run
args:      (<gtsfm.common.gtsfm_data.GtsfmData object at 0x7f3ef0165100>, [R: [
        0.607928, 0.00401813, -0.793982;
        0.0331198, 0.998989, 0.0304144;
        0.793301, -0.0447863, 0.60718
]
t:     6.00406 -0.00250571     1.39347
, R: [
        0.831711, -0.00881482, -0.555139;
        0.0243031, 0.999494, 0.0205405;
        0.554677, -0.0305754, 0.831504
]
t:     4.95205 -0.00204004     0.22173
, R: [
        0.983981, -0.00487522, -0.178209;
        0.00940524, 0.999654, 0.0245838;
        0.178027, -0.0258661, 0.983686
]
t:    3.47209 -0.0521855  -0.227345
, R: [
        0.999968, -0.001583, -0.00783759;
        0.00178767, 0.999656, 0.0261754;
        0.00779346, -0.0261885, 0.999627
]
t:    1.77286 0.00158765  -0.388105
, R: [
        0.998957, -0.00134614, -0.0456445;
        0.00298639, 0.999351, 0.0358864;
        0.0455666, -0.0359853, 0.998313
]
t: -0.128728 0.0693803 -0.259196
, R: [
        0.997825, 0.00081373, 0.0659063;
        -0.00193781, 0.999854, 0.0169937;
        -0.0658828, -0.0170844, 0.997681
]
t:   -1.7409 0.0312413 -0.140199
, R: [
        0.981575, -0.00033445, 0.191078;
        -0.00527822, 0.999
kwargs:    {}
Exception: AttributeError("'float' object has no attribute 'tolist'")

Traceback (most recent call last):
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 91, in <module>
    run_scene_optimizer(args)
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 44, in run_scene_optimizer
    sfm_result = sfm_result_graph.compute()
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2707, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2021, in gather
    return self.sync(
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 862, in sync
    return sync(
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    raise exc.with_traceback(tb)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 321, in f
    result[0] = yield future
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 1886, in _gather
    raise exception.with_traceback(traceback)
  File "/home/tdriver6/Documents/gtsfm/gtsfm/bundle/bundle_adjustment.py", line 162, in run
    ba_metrics.add_metrics(get_metrics_from_sfm_data(filtered_result, suffix="_filtered"))
  File "/home/tdriver6/Documents/gtsfm/gtsfm/bundle/bundle_adjustment.py", line 143, in get_metrics_from_sfm_data
    metrics.append(GtsfmMetric(f"reprojection_errors{suffix}_px", sfm_data.get_scene_reprojection_errors()))
  File "/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py", line 113, in __init__
    self._summary = self._create_summary(data)
  File "/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py", line 176, in _create_summary
    "median": np.nanmedian(data).tolist(),
AttributeError: 'float' object has no attribute 'tolist'(data).tolist(),
/home/tdriver6/Documents/gtsfm/gtsfm/evaluation/metrics.py:175: RuntimeWarning: All-NaN slice encountered
  "max": np.nanmax(data).tolist(),
/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/numpy/lib/nanfunctions.py:1113: RuntimeWarning: All-NaN slice encountered
  r, k = function_base._ureduce(a, func=_nanmedian, axis=axis, out=out,
distributed.worker - WARNING - Compute Failed
Function:  run
args:      (<gtsfm.common.gtsfm_data.GtsfmData object at 0x7f3ef0165100>, [R: [
        0.607928, 0.00401813, -0.793982;
        0.0331198, 0.998989, 0.0304144;
        0.793301, -0.0447863, 0.60718
]
t:     6.00406 -0.00250571     1.39347
, R: [
        0.831711, -0.00881482, -0.555139;
        0.0243031, 0.999494, 0.0205405;
        0.554677, -0.0305754, 0.831504
]
t:     4.95205 -0.00204004     0.22173
, R: [
        0.983981, -0.00487522, -0.178209;
        0.00940524, 0.999654, 0.0245838;
        0.178027, -0.0258661, 0.983686
]
t:    3.47209 -0.0521855  -0.227345
, R: [
        0.999968, -0.001583, -0.00783759;
        0.00178767, 0.999656, 0.0261754;
        0.00779346, -0.0261885, 0.999627
]
t:    1.77286 0.00158765  -0.388105
, R: [
        0.998957, -0.00134614, -0.0456445;
        0.00298639, 0.999351, 0.0358864;
        0.0455666, -0.0359853, 0.998313
]
t: -0.128728 0.0693803 -0.259196
, R: [
        0.997825, 0.00081373, 0.0659063;
        -0.00193781, 0.999854, 0.0169937;
        -0.0658828, -0.0170844, 0.997681
]
t:   -1.7409 0.0312413 -0.140199
, R: [
        0.981575, -0.00033445, 0.191078;
        -0.00527822, 0.999
kwargs:    {}
Exception: AttributeError("'float' object has no attribute 'tolist'")

Traceback (most recent call last):
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 91, in <module>
    run_scene_optimizer(args)
  File "gtsfm/runner/run_scene_optimizer_colmaploader.py", line 44, in run_scene_optimizer
    sfm_result = sfm_result_graph.compute()
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2707, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 2021, in gather
    return self.sync(
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 862, in sync
    return sync(
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 338, in sync
    raise exc.with_traceback(tb)
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/utils.py", line 321, in f
    result[0] = yield future
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/tdriver6/anaconda3/envs/gtsfm-v1/lib/python3.8/site-packages/distributed/client.py", line 1886, in _gather
    raise exception.with_traceback(trac [...]

2021-09-08 15:59 UTC, akshay-krishnan commented
In File "/home/tdriver6/Documents/gtsfm/gtsfm/bundle/bundle_adjustment.py", line 143 could you try printing `sfm_data.get_scene_reprojection_errors()` to debug this?

2021-09-08 16:09 UTC, akshay-krishnan commented
I think its possible that all numbers are NaN, and we cannot do to_list() in that case. 
```
>>> np.nanmedian([np.NaN]).tolist()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'float' object has no attribute 'tolist'
```
So maybe we should add this check to https://github.com/borglab/gtsfm/blob/2072a9893d878aa99dfce5c66ab361991034bef4/gtsfm/evaluation/metrics.py#L170

2021-09-08 16:40 UTC, johnwlambert commented
I really want us to find out where in the pipeline we get all NaNs, and figure out why we get all NaNs, before we check in this, because I think this is a good opportunity to find the deeper bug.

2021-09-10 05:32 UTC, akshay-krishnan commented
@travisdriver could you check if this happens with the SIFT front end as well? I tried reproducing this on my machine, did everything as you mentioned except I used the sift_front_end.yaml config, and things worked fine. I cannot run the deep_front_end on my machine.

2021-09-10 13:57 UTC, travisdriver commented
> @travisdriver could you check if this happens with the SIFT front end as well? I tried reproducing this on my machine, did everything as you mentioned except I used the sift_front_end.yaml config, and things worked fine. I cannot run the deep_front_end on my machine.

You ran on master right?

Also, the bug had went away until I reinstalled the linux environment with the most recent changes. Did you reinstall the environment first?

2021-09-10 16:03 UTC, akshay-krishnan commented
> > @travisdriver could you check if this happens with the SIFT front end as well? I tried reproducing this on my machine, did everything as you mentioned except I used the sift_front_end.yaml config, and things worked fine. I cannot run the deep_front_end on my machine.
> 
> You ran on master right?
> 
> Also, the bug had went away until I reinstalled the linux environment with the most recent changes. Did you reinstall the environment first?

Yes, I reinstalled the environment (from master), ran on both master and this branch (the difference is just the fix in GtsfmMetric).

2021-09-10 16:09 UTC, akshay-krishnan requested changes

2021-09-10 16:09 UTC, akshay-krishnan commented on gtsfm/evaluation/metrics.py
>              return {"min": np.NaN, "max": np.NaN, "median": np.NaN, "mean": np.NaN, "stddev": np.NaN}
could you change to something like this? 
```
nan_summary ={"min": np.NaN, "max": np.NaN, "median": np.NaN, "mean": np.NaN, "stddev": np.NaN}
if data.size == 0:
    log warning ("{metric_name} is empty, summary contains NaNs.")
    return nan_summary
if np.isnan(data).all():
   log warning ("all values in {metric_name} are NaNs, hence summary contains NaNs")
   return nan_summary
```
I am a bit undecided about whether we need a NaN summary or just an empty summary, or no summary at all for these cases.

2021-11-26 19:01 UTC, travisdriver commented
Not sure if this is still another issue, but this branch is likely irrelevant at this point anyways.

2021-12-30 01:53 UTC, johnwlambert commented
@travisdriver let's go ahead and merge this. I am able to reproduce this bug now with numpy 1.19 (when nanmean of an array of NaNs was undefined) but in 1.21.4 there is default behavior defined for this.

2021-12-30 04:39 UTC, johnwlambert approved these changes

2021-12-30 04:40 UTC, merged