Color inliers and outliers (w.r.t. GT poses) green/red, and make CI upload these images as artifacts.
borglab/gtsfm pull request #343
Opened 2021-10-10 03:44 UTC by johnwlambert

Color inliers and outliers (w.r.t. GT poses) green/red, and make CI upload these images as artifacts.

Currently CI does not generate these figures as artifacts.
Currently, locally, even when GT pose is available, we use random colors for each correspondence, which makes it hard to see when Sampson error classifies correspondences correctly.

This provides important info bout where we expect to see outlier 3d points in free space after BA. This "per-correspondence ground truth" also will allow us to start using this information to analyze the purity of our tracks in DA.

Examples from skydio-8, deep front end:
![1_7](https://user-images.githubusercontent.com/16724970/136681186-0f837f2f-cea1-4dd3-934f-8da3082eeed6.jpg)

![0_4](https://user-images.githubusercontent.com/16724970/136681198-52bdb71f-09c6-4b6d-a23b-ae724ef0f70b.jpg)

2021-10-10 21:31 UTC, akshay-krishnan requested changes

2021-10-10 21:31 UTC, akshay-krishnan commented on gtsfm/utils/metrics.py
> +            (using GT epipolar geometry).
I dont think this is a good API, its like returning a mask and a non-zero count of the mask. The user could just count the nonzeros outside.

2021-10-10 21:31 UTC, akshay-krishnan commented on gtsfm/two_view_estimator.py
> +    return num_inliers_gt_model, inlier_ratio_gt_model, v_corr_idxs_inlier_mask_gt
even here, ideally we only need to return the mask, num inliers are inlier ratio can be computed outside.

2021-10-10 21:34 UTC, akshay-krishnan commented
> The main issue I see is that we turn on the visualization by default, and upload it to CI. I think we should avoid this.

+1, I'll add the reasons: 
- increases CI time, 
- waste of resources (both space and compute) as this runs for all commits on all PRs and we dont have many PRs on the frontend. 
- its not what the CI is meant for, are there any uses to the visualization other than debugging?

2021-10-11 13:33 UTC, johnwlambert commented
@ayushbaid @akshay-krishnan thanks for taking a look. I agree that most users wouldnt want the "save 2-view viz" setting turned on locally, since it blows up the disk. But in the CI, it's free. Maybe it should be a CLI arg we can turn on in the CI then?

I think these plots that the CI generates are quite informative. For example, the matches here look great, but Sampson at 4 px for 760p says they're wrong. So this threshold must be bad:
![1_10](https://user-images.githubusercontent.com/16724970/136798757-9e17a389-3ff7-425a-8859-15df0b90f627.jpg)

On the other hand, we get a lot of visibility into why this dataset is hard (object symmetry):
![0_24](https://user-images.githubusercontent.com/16724970/136798881-da395854-d51b-4449-ad82-900a37e07cdd.jpg)
![0_6](https://user-images.githubusercontent.com/16724970/136798871-f11a82f6-1b6a-4d16-9b84-88b7ea7048c8.jpg)
![0_11](https://user-images.githubusercontent.com/16724970/136798876-8c62c84d-9018-46e8-aea2-7e4c6f60b6b5.jpg)

2021-10-11 13:43 UTC, travisdriver commented
The coloring of inliers and outliers is also in [#295](https://github.com/borglab/gtsfm/pull/295)

2021-10-13 02:11 UTC, ayushbaid approved these changes

2021-10-13 02:20 UTC, merged